  
sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f dockerfile .

script:
  - docker run stephengrider/docker-react npm run test --env=jsdom --coverage 


